name: Check File Changes

on:
  pull_request:
    paths:
      - '**'

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check for modified files outside of 'members/' directory
      run: |
        # Check the modified files
        MODIFIED_FILES=$(git diff --name-only HEAD^ HEAD)

        # Check if there are files outside the 'members/' directory that were modified
        NON_MEMBER_FILES=$(echo "$MODIFIED_FILES" | grep -v '^members/')
        
        if [ -n "$NON_MEMBER_FILES" ]; then
          echo "Error: The following non-members/ files were modified:"
          echo "$NON_MEMBER_FILES"
          exit 1
        else
          echo "Only members/ directory was modified. Proceeding..."
        fi
